### ISSUE TITLE
我发现它很适合来作为笔记的导航图，能否支持下载时，指定图片宽高

### ISSUE THREAD

**Issue by bwensun** [pearmini/colorfu#86]
![image](https://user-images.githubusercontent.com/37960247/146307926-750fe833-e6ce-4fef-af93-06c3e40781d6.png)

**Comment by pearmini** [comment]
很好的提议！其实感觉就是可以自定义画板的大小，目前的画板大小可以理解为屏幕大小。如果下载自定义画板大小的图片，其实就是相对于下载的时候指定图片大小，你觉得这样怎样？

**Comment by bwensun** [comment]
我觉得可以 至少有一个预览效果
